apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-hellokube.fullname" . }}
  labels:
    {{- include "go-hellokube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.service.targetPort}}
      name: http
  selector:
    {{- include "go-hellokube.selectorLabels" . | nindent 4 }}
